### PR TITLE
Doc updated for IBM ACE version 7 changes

### PR DESCRIPTION
**Pull request by AjeetGupta**

### CODE REVIEW

**Comment by osmanburucu** [comment]
please fix the versionnumber on all the files

in the bottom of each file a "nav bar" is available where the latest version can be downloaded. On some of the files the number of the version was not changed, but the link was updated. Example: 
[6.1134007](https://raw.githubusercontent.com/UrbanCode/IBM-UCD-PLUGINS/main/files/ibm-ace/ucd-plugins-ibm-ace-7.1138742.zip)

on other files it was not changed.

you need to change
[6.1134007](https://raw.githubusercontent.com/UrbanCode/IBM-UCD-PLUGINS/main/files/ibm-ace/ucd-plugins-ibm-ace-6.1134007.zip)
to 
[7.1138742](https://raw.githubusercontent.com/UrbanCode/IBM-UCD-PLUGINS/main/files/ibm-ace/ucd-plugins-ibm-ace-7.1138742.zip)

in those following files in the ibm-ace directory:
* README.md
* downloads.md
* overview.md
* steps.md
* usage.md

AND update the main README.md here https://github.com/AjeetGupta/IBM-UCx-PLUGIN-DOCS/tree/main/docs/UCD

**Comment by osmanburucu** [comment]
Please check comments
https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28#issuecomment-1204024240

Sincerely,

Ing. Osman Burucu
Product Manager UrbanCode Family
IBM Automation – DevOps
+43 664 6186507 Mobile
+43 1 21145 4746 Office
***@***.***

IBM Let’s create a better software delivery experience

From: AjeetGupta ***@***.***>
Date: Wednesday, 3. August 2022 at 17:10
To: UrbanCode/IBM-UCx-PLUGIN-DOCS ***@***.***>
Cc: Osman Burucu ***@***.***>, Review requested ***@***.***>
Subject: [EXTERNAL] [UrbanCode/IBM-UCx-PLUGIN-DOCS] Doc updated for IBM ACE version 7 changes (PR #28)
You can view, comment on, or merge this pull request online at: https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28 Commit Summary a22ac36 Doc updated for IBM ACE version 7 changes File Changes (3 files ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd
________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28<https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28>

Commit Summary
·         a22ac36<https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28/commits/a22ac369342084c26e7dc23113874f0f4033ba66> Doc updated for IBM ACE version 7 changes
File Changes

(3 files<https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28/files>)
·         M docs/UCD/ibm-ace/README.md<https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28/files#diff-d4505cc400c1100253b254531af2045e717a1da366a068df03395eee5caa8b73> (2)
·         M docs/UCD/ibm-ace/downloads.md<https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28/files#diff-207368e24f12737c101f15dce2161b480314d4b36e01a553e03300375750476e> (1)
·         M docs/UCD/ibm-ace/overview.md<https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28/files#diff-88695065d35874018e03535f03ee5f35d044d5deab5a25a4fd171ac7f22f3463> (8)
Patch Links:
·         https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28.patch<https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28.patch>
·         https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28.diff<https://github.com/UrbanCode/IBM-UCx-PLUGIN-DOCS/pull/28.diff>

**Review by osmanburucu — CHANGES_REQUESTED** [review]
please fix the versionnumber on all the files

in the bottom of each file a "nav bar" is available where the latest version can be downloaded. On some of the files the number of the version was not changed, but the link was updated. Example:
[6.1134007](https://raw.githubusercontent.com/UrbanCode/IBM-UCD-PLUGINS/main/files/ibm-ace/ucd-plugins-ibm-ace-7.1138742.zip)

on other files it was not changed.

you need to change
[6.1134007](https://raw.githubusercontent.com/UrbanCode/IBM-UCD-PLUGINS/main/files/ibm-ace/ucd-plugins-ibm-ace-6.1134007.zip)
to
[7.1138742](https://raw.githubusercontent.com/UrbanCode/IBM-UCD-PLUGINS/main/files/ibm-ace/ucd-plugins-ibm-ace-7.1138742.zip)

in those following files in the ibm-ace directory:

    README.md
    downloads.md
    overview.md
    steps.md
    usage.md

AND update the main README.md here https://github.com/AjeetGupta/IBM-UCx-PLUGIN-DOCS/tree/main/docs/UCD

**Comment by AjeetGupta** [comment]
Hi @osmanburucu-ibm , addressed requested changes , Please review and let us know,  if still needed anything to change.

**Comment by osmanburucu** [comment]
Done, I have also updated the file link as the default did not work, no idea why..

Sincerely,

Ing. Osman Burucu
Product Manager UrbanCode Family
IBM Automation – DevOps
+43 664 6186507 Mobile
+43 1 21145 4746 Office
***@***.***

IBM Let’s create a better software delivery experience

From: AjeetGupta ***@***.***>
Date: Thursday, 4. August 2022 at 10:21
To: UrbanCode/IBM-UCx-PLUGIN-DOCS ***@***.***>
Cc: Osman Burucu ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [UrbanCode/IBM-UCx-PLUGIN-DOCS] Doc updated for IBM ACE version 7 changes (PR #28)
Hi @osmanburucu-ibm , addressed requested changes , Please review and let us know, if still needed anything to change. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @osmanburucu-ibm<https://github.com/osmanburucu-ibm> , addressed requested changes , Please review and let us know, if still needed anything to change.

**Pull request merged**
